package com.example.my_blog.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class LArticle implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_article.id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_article.user_id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_article.category_id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_article.article_cover
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private String articleCover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_article.article_title
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private String articleTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_article.article_type
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private Integer articleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_article.is_top
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private Integer isTop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_article.is_delete
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_article.is_recommend
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private Integer isRecommend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_article.status
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_article.create_time
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */

    @JsonFormat(pattern = "yyyy-MM")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_article.update_time
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_article.zan
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private Integer zan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_article.reading
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private Integer reading;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_article.article_text
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private String articleText;

    private String dateToString;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table l_article
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private static final long serialVersionUID = 1L;

    public String getDateToString() {
        return dateToString;
    }

    public void setDateToString(String dateToString) {
        this.dateToString = dateToString;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_article.id
     *
     * @return the value of l_article.id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_article.id
     *
     * @param id the value for l_article.id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_article.user_id
     *
     * @return the value of l_article.user_id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_article.user_id
     *
     * @param userId the value for l_article.user_id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_article.category_id
     *
     * @return the value of l_article.category_id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_article.category_id
     *
     * @param categoryId the value for l_article.category_id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_article.article_cover
     *
     * @return the value of l_article.article_cover
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public String getArticleCover() {
        return articleCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_article.article_cover
     *
     * @param articleCover the value for l_article.article_cover
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setArticleCover(String articleCover) {
        this.articleCover = articleCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_article.article_title
     *
     * @return the value of l_article.article_title
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_article.article_title
     *
     * @param articleTitle the value for l_article.article_title
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_article.article_type
     *
     * @return the value of l_article.article_type
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Integer getArticleType() {
        return articleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_article.article_type
     *
     * @param articleType the value for l_article.article_type
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setArticleType(Integer articleType) {
        this.articleType = articleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_article.is_top
     *
     * @return the value of l_article.is_top
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Integer getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_article.is_top
     *
     * @param isTop the value for l_article.is_top
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setIsTop(Integer isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_article.is_delete
     *
     * @return the value of l_article.is_delete
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_article.is_delete
     *
     * @param isDelete the value for l_article.is_delete
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_article.is_recommend
     *
     * @return the value of l_article.is_recommend
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Integer getIsRecommend() {
        return isRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_article.is_recommend
     *
     * @param isRecommend the value for l_article.is_recommend
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setIsRecommend(Integer isRecommend) {
        this.isRecommend = isRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_article.status
     *
     * @return the value of l_article.status
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_article.status
     *
     * @param status the value for l_article.status
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_article.create_time
     *
     * @return the value of l_article.create_time
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_article.create_time
     *
     * @param createTime the value for l_article.create_time
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_article.update_time
     *
     * @return the value of l_article.update_time
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_article.update_time
     *
     * @param updateTime the value for l_article.update_time
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_article.zan
     *
     * @return the value of l_article.zan
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Integer getZan() {
        return zan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_article.zan
     *
     * @param zan the value for l_article.zan
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setZan(Integer zan) {
        this.zan = zan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_article.reading
     *
     * @return the value of l_article.reading
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Integer getReading() {
        return reading;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_article.reading
     *
     * @param reading the value for l_article.reading
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setReading(Integer reading) {
        this.reading = reading;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_article.article_text
     *
     * @return the value of l_article.article_text
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public String getArticleText() {
        return articleText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_article.article_text
     *
     * @param articleText the value for l_article.article_text
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setArticleText(String articleText) {
        this.articleText = articleText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", articleCover=").append(articleCover);
        sb.append(", articleTitle=").append(articleTitle);
        sb.append(", articleType=").append(articleType);
        sb.append(", isTop=").append(isTop);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", isRecommend=").append(isRecommend);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", zan=").append(zan);
        sb.append(", reading=").append(reading);
        sb.append(", articleText=").append(articleText);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}