package com.example.my_blog.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class LComment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_comment.id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_comment.cm_nickname
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private String cmNickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_comment.cm_email
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private String cmEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_comment.cm_qq
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private String cmQq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_comment.cm_text
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private String cmText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_comment.cm_time
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date cmTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_comment.cm_zan
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private Integer cmZan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_comment.cm_delete
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private Integer cmDelete;

    private Integer articleId;
    private Integer cmParents;

    public Integer getArticleId() {
        return articleId;
    }

    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    public Integer getCmParents() {
        return cmParents;
    }

    public void setCmParents(Integer cmParents) {
        this.cmParents = cmParents;
    }

    public String getCmQq() {
        return cmQq;
    }

    public void setCmQq(String cmQq) {
        this.cmQq = cmQq;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table l_comment
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_comment.id
     *
     * @return the value of l_comment.id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_comment.id
     *
     * @param id the value for l_comment.id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_comment.cm_nickname
     *
     * @return the value of l_comment.cm_nickname
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public String getCmNickname() {
        return cmNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_comment.cm_nickname
     *
     * @param cmNickname the value for l_comment.cm_nickname
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setCmNickname(String cmNickname) {
        this.cmNickname = cmNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_comment.cm_email
     *
     * @return the value of l_comment.cm_email
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public String getCmEmail() {
        return cmEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_comment.cm_email
     *
     * @param cmEmail the value for l_comment.cm_email
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setCmEmail(String cmEmail) {
        this.cmEmail = cmEmail;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_comment.cm_text
     *
     * @return the value of l_comment.cm_text
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public String getCmText() {
        return cmText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_comment.cm_text
     *
     * @param cmText the value for l_comment.cm_text
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setCmText(String cmText) {
        this.cmText = cmText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_comment.cm_time
     *
     * @return the value of l_comment.cm_time
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Date getCmTime() {
        return cmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_comment.cm_time
     *
     * @param cmTime the value for l_comment.cm_time
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setCmTime(Date cmTime) {
        this.cmTime = cmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_comment.cm_zan
     *
     * @return the value of l_comment.cm_zan
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Integer getCmZan() {
        return cmZan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_comment.cm_zan
     *
     * @param cmZan the value for l_comment.cm_zan
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setCmZan(Integer cmZan) {
        this.cmZan = cmZan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_comment.cm_delete
     *
     * @return the value of l_comment.cm_delete
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Integer getCmDelete() {
        return cmDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_comment.cm_delete
     *
     * @param cmDelete the value for l_comment.cm_delete
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setCmDelete(Integer cmDelete) {
        this.cmDelete = cmDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_comment
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cmNickname=").append(cmNickname);
        sb.append(", cmEmail=").append(cmEmail);
        sb.append(", cmQq=").append(cmQq);
        sb.append(", cmText=").append(cmText);
        sb.append(", cmTime=").append(cmTime);
        sb.append(", cmZan=").append(cmZan);
        sb.append(", cmDelete=").append(cmDelete);
        sb.append(", cmParents=").append(cmParents);
        sb.append(", articleId=").append(articleId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}