package com.example.my_blog.model;

import java.io.Serializable;
import java.util.Date;

public class LFriend implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_friend.id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_friend.name
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_friend.color
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_friend.avatar
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_friend.url
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_friend.introduction
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_friend.create_time
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_friend.update_time
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private Date updateTime;

    private Integer pass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table l_friend
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_friend.id
     *
     * @return the value of l_friend.id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_friend.id
     *
     * @param id the value for l_friend.id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_friend.name
     *
     * @return the value of l_friend.name
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_friend.name
     *
     * @param name the value for l_friend.name
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_friend.color
     *
     * @return the value of l_friend.color
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_friend.color
     *
     * @param color the value for l_friend.color
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_friend.avatar
     *
     * @return the value of l_friend.avatar
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_friend.avatar
     *
     * @param avatar the value for l_friend.avatar
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_friend.url
     *
     * @return the value of l_friend.url
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_friend.url
     *
     * @param url the value for l_friend.url
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_friend.introduction
     *
     * @return the value of l_friend.introduction
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_friend.introduction
     *
     * @param introduction the value for l_friend.introduction
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_friend.create_time
     *
     * @return the value of l_friend.create_time
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_friend.create_time
     *
     * @param createTime the value for l_friend.create_time
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_friend.update_time
     *
     * @return the value of l_friend.update_time
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_friend.update_time
     *
     * @param updateTime the value for l_friend.update_time
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getPass() {
        return pass;
    }

    public void setPass(Integer pass) {
        this.pass = pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_friend
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", color=").append(color);
        sb.append(", avatar=").append(avatar);
        sb.append(", url=").append(url);
        sb.append(", introduction=").append(introduction);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}