package com.example.my_blog.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LSuibiExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table l_suibi
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table l_suibi
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table l_suibi
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_suibi
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public LSuibiExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_suibi
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_suibi
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_suibi
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_suibi
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_suibi
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_suibi
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_suibi
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_suibi
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_suibi
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_suibi
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table l_suibi
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSuibiTextIsNull() {
            addCriterion("suibi_text is null");
            return (Criteria) this;
        }

        public Criteria andSuibiTextIsNotNull() {
            addCriterion("suibi_text is not null");
            return (Criteria) this;
        }

        public Criteria andSuibiTextEqualTo(String value) {
            addCriterion("suibi_text =", value, "suibiText");
            return (Criteria) this;
        }

        public Criteria andSuibiTextNotEqualTo(String value) {
            addCriterion("suibi_text <>", value, "suibiText");
            return (Criteria) this;
        }

        public Criteria andSuibiTextGreaterThan(String value) {
            addCriterion("suibi_text >", value, "suibiText");
            return (Criteria) this;
        }

        public Criteria andSuibiTextGreaterThanOrEqualTo(String value) {
            addCriterion("suibi_text >=", value, "suibiText");
            return (Criteria) this;
        }

        public Criteria andSuibiTextLessThan(String value) {
            addCriterion("suibi_text <", value, "suibiText");
            return (Criteria) this;
        }

        public Criteria andSuibiTextLessThanOrEqualTo(String value) {
            addCriterion("suibi_text <=", value, "suibiText");
            return (Criteria) this;
        }

        public Criteria andSuibiTextLike(String value) {
            addCriterion("suibi_text like", value, "suibiText");
            return (Criteria) this;
        }

        public Criteria andSuibiTextNotLike(String value) {
            addCriterion("suibi_text not like", value, "suibiText");
            return (Criteria) this;
        }

        public Criteria andSuibiTextIn(List<String> values) {
            addCriterion("suibi_text in", values, "suibiText");
            return (Criteria) this;
        }

        public Criteria andSuibiTextNotIn(List<String> values) {
            addCriterion("suibi_text not in", values, "suibiText");
            return (Criteria) this;
        }

        public Criteria andSuibiTextBetween(String value1, String value2) {
            addCriterion("suibi_text between", value1, value2, "suibiText");
            return (Criteria) this;
        }

        public Criteria andSuibiTextNotBetween(String value1, String value2) {
            addCriterion("suibi_text not between", value1, value2, "suibiText");
            return (Criteria) this;
        }

        public Criteria andSuibiImgIsNull() {
            addCriterion("suibi_img is null");
            return (Criteria) this;
        }

        public Criteria andSuibiImgIsNotNull() {
            addCriterion("suibi_img is not null");
            return (Criteria) this;
        }

        public Criteria andSuibiImgEqualTo(String value) {
            addCriterion("suibi_img =", value, "suibiImg");
            return (Criteria) this;
        }

        public Criteria andSuibiImgNotEqualTo(String value) {
            addCriterion("suibi_img <>", value, "suibiImg");
            return (Criteria) this;
        }

        public Criteria andSuibiImgGreaterThan(String value) {
            addCriterion("suibi_img >", value, "suibiImg");
            return (Criteria) this;
        }

        public Criteria andSuibiImgGreaterThanOrEqualTo(String value) {
            addCriterion("suibi_img >=", value, "suibiImg");
            return (Criteria) this;
        }

        public Criteria andSuibiImgLessThan(String value) {
            addCriterion("suibi_img <", value, "suibiImg");
            return (Criteria) this;
        }

        public Criteria andSuibiImgLessThanOrEqualTo(String value) {
            addCriterion("suibi_img <=", value, "suibiImg");
            return (Criteria) this;
        }

        public Criteria andSuibiImgLike(String value) {
            addCriterion("suibi_img like", value, "suibiImg");
            return (Criteria) this;
        }

        public Criteria andSuibiImgNotLike(String value) {
            addCriterion("suibi_img not like", value, "suibiImg");
            return (Criteria) this;
        }

        public Criteria andSuibiImgIn(List<String> values) {
            addCriterion("suibi_img in", values, "suibiImg");
            return (Criteria) this;
        }

        public Criteria andSuibiImgNotIn(List<String> values) {
            addCriterion("suibi_img not in", values, "suibiImg");
            return (Criteria) this;
        }

        public Criteria andSuibiImgBetween(String value1, String value2) {
            addCriterion("suibi_img between", value1, value2, "suibiImg");
            return (Criteria) this;
        }

        public Criteria andSuibiImgNotBetween(String value1, String value2) {
            addCriterion("suibi_img not between", value1, value2, "suibiImg");
            return (Criteria) this;
        }

        public Criteria andSuibiCtimeIsNull() {
            addCriterion("suibi_ctime is null");
            return (Criteria) this;
        }

        public Criteria andSuibiCtimeIsNotNull() {
            addCriterion("suibi_ctime is not null");
            return (Criteria) this;
        }

        public Criteria andSuibiCtimeEqualTo(Date value) {
            addCriterion("suibi_ctime =", value, "suibiCtime");
            return (Criteria) this;
        }

        public Criteria andSuibiCtimeNotEqualTo(Date value) {
            addCriterion("suibi_ctime <>", value, "suibiCtime");
            return (Criteria) this;
        }

        public Criteria andSuibiCtimeGreaterThan(Date value) {
            addCriterion("suibi_ctime >", value, "suibiCtime");
            return (Criteria) this;
        }

        public Criteria andSuibiCtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("suibi_ctime >=", value, "suibiCtime");
            return (Criteria) this;
        }

        public Criteria andSuibiCtimeLessThan(Date value) {
            addCriterion("suibi_ctime <", value, "suibiCtime");
            return (Criteria) this;
        }

        public Criteria andSuibiCtimeLessThanOrEqualTo(Date value) {
            addCriterion("suibi_ctime <=", value, "suibiCtime");
            return (Criteria) this;
        }

        public Criteria andSuibiCtimeIn(List<Date> values) {
            addCriterion("suibi_ctime in", values, "suibiCtime");
            return (Criteria) this;
        }

        public Criteria andSuibiCtimeNotIn(List<Date> values) {
            addCriterion("suibi_ctime not in", values, "suibiCtime");
            return (Criteria) this;
        }

        public Criteria andSuibiCtimeBetween(Date value1, Date value2) {
            addCriterion("suibi_ctime between", value1, value2, "suibiCtime");
            return (Criteria) this;
        }

        public Criteria andSuibiCtimeNotBetween(Date value1, Date value2) {
            addCriterion("suibi_ctime not between", value1, value2, "suibiCtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table l_suibi
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 28 13:00:42 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table l_suibi
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}