package com.example.my_blog.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class LSuibi implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_suibi.id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_suibi.suibi_text
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private String suibiText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_suibi.suibi_img
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private String suibiImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_suibi.suibi_ctime
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date suibiCtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table l_suibi
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_suibi.id
     *
     * @return the value of l_suibi.id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_suibi.id
     *
     * @param id the value for l_suibi.id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_suibi.suibi_text
     *
     * @return the value of l_suibi.suibi_text
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public String getSuibiText() {
        return suibiText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_suibi.suibi_text
     *
     * @param suibiText the value for l_suibi.suibi_text
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setSuibiText(String suibiText) {
        this.suibiText = suibiText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_suibi.suibi_img
     *
     * @return the value of l_suibi.suibi_img
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public String getSuibiImg() {
        return suibiImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_suibi.suibi_img
     *
     * @param suibiImg the value for l_suibi.suibi_img
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setSuibiImg(String suibiImg) {
        this.suibiImg = suibiImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_suibi.suibi_ctime
     *
     * @return the value of l_suibi.suibi_ctime
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Date getSuibiCtime() {
        return suibiCtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_suibi.suibi_ctime
     *
     * @param suibiCtime the value for l_suibi.suibi_ctime
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setSuibiCtime(Date suibiCtime) {
        this.suibiCtime = suibiCtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_suibi
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", suibiText=").append(suibiText);
        sb.append(", suibiImg=").append(suibiImg);
        sb.append(", suibiCtime=").append(suibiCtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}