package com.example.my_blog.model;

import java.io.Serializable;
import java.util.Date;

public class LTag implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_tag.id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_tag.tag_name
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private String tagName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_tag.tag_color
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private String tagColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_tag.create_time
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_tag.update_time
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table l_tag
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_tag.id
     *
     * @return the value of l_tag.id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_tag.id
     *
     * @param id the value for l_tag.id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_tag.tag_name
     *
     * @return the value of l_tag.tag_name
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_tag.tag_name
     *
     * @param tagName the value for l_tag.tag_name
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_tag.tag_color
     *
     * @return the value of l_tag.tag_color
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public String getTagColor() {
        return tagColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_tag.tag_color
     *
     * @param tagColor the value for l_tag.tag_color
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setTagColor(String tagColor) {
        this.tagColor = tagColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_tag.create_time
     *
     * @return the value of l_tag.create_time
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_tag.create_time
     *
     * @param createTime the value for l_tag.create_time
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_tag.update_time
     *
     * @return the value of l_tag.update_time
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_tag.update_time
     *
     * @param updateTime the value for l_tag.update_time
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_tag
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tagName=").append(tagName);
        sb.append(", tagColor=").append(tagColor);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}