package com.example.my_blog.model;

import java.io.Serializable;

public class LUserRole implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_user_role.id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_user_role.user_id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_user_role.role_id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table l_user_role
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_user_role.id
     *
     * @return the value of l_user_role.id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_user_role.id
     *
     * @param id the value for l_user_role.id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_user_role.user_id
     *
     * @return the value of l_user_role.user_id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_user_role.user_id
     *
     * @param userId the value for l_user_role.user_id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_user_role.role_id
     *
     * @return the value of l_user_role.role_id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_user_role.role_id
     *
     * @param roleId the value for l_user_role.role_id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_user_role
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    @Override
    public String toString() {
        return "LUserRole{" +
                "id=" + id +
                ", userId=" + userId +
                ", roleId=" + roleId +
                '}';
    }
}