package com.example.my_blog.model;

import java.io.Serializable;
import java.util.Date;

public class LVisitLog implements Serializable {

    private Integer id;

    private String visit;
    //    操作
    private String logOperation;
    //    页面
    private String page;

    private String ipAddress;

    private String ipSource;
    //    操作系统
    private String os;
    //    浏览器
    private String browser;

    private Date createTime;


    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_visit_log.id
     *
     * @param id the value for l_visit_log.id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_visit_log.page
     *
     * @return the value of l_visit_log.page
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public String getPage() {
        return page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_visit_log.page
     *
     * @param page the value for l_visit_log.page
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setPage(String page) {
        this.page = page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_visit_log.ip_address
     *
     * @return the value of l_visit_log.ip_address
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_visit_log.ip_address
     *
     * @param ipAddress the value for l_visit_log.ip_address
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_visit_log.ip_source
     *
     * @return the value of l_visit_log.ip_source
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public String getIpSource() {
        return ipSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_visit_log.ip_source
     *
     * @param ipSource the value for l_visit_log.ip_source
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setIpSource(String ipSource) {
        this.ipSource = ipSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_visit_log.os
     *
     * @return the value of l_visit_log.os
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public String getOs() {
        return os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_visit_log.os
     *
     * @param os the value for l_visit_log.os
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setOs(String os) {
        this.os = os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_visit_log.browser
     *
     * @return the value of l_visit_log.browser
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public String getBrowser() {
        return browser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_visit_log.browser
     *
     * @param browser the value for l_visit_log.browser
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setBrowser(String browser) {
        this.browser = browser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_visit_log.create_time
     *
     * @return the value of l_visit_log.create_time
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_visit_log.create_time
     *
     * @param createTime the value for l_visit_log.create_time
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_visit_log
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */

    public String getVisit() {
        return visit;
    }

    public void setVisit(String visit) {
        this.visit = visit;
    }

    public String getLogOperation() {
        return logOperation;
    }

    public void setLogOperation(String logOperation) {
        this.logOperation = logOperation;
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    @Override
    public String toString() {
        return "LVisitLog{" +
                "id=" + id +
                ", visit='" + visit + '\'' +
                ", logOperation='" + logOperation + '\'' +
                ", page='" + page + '\'' +
                ", ipAddress='" + ipAddress + '\'' +
                ", ipSource='" + ipSource + '\'' +
                ", os='" + os + '\'' +
                ", browser='" + browser + '\'' +
                ", createTime=" + createTime +
                '}';
    }
}