package com.example.my_blog.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LXiangceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table l_xiangce
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table l_xiangce
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table l_xiangce
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_xiangce
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public LXiangceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_xiangce
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_xiangce
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_xiangce
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_xiangce
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_xiangce
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_xiangce
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_xiangce
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_xiangce
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_xiangce
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_xiangce
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table l_xiangce
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andXcImagesIsNull() {
            addCriterion("xc_images is null");
            return (Criteria) this;
        }

        public Criteria andXcImagesIsNotNull() {
            addCriterion("xc_images is not null");
            return (Criteria) this;
        }

        public Criteria andXcImagesEqualTo(String value) {
            addCriterion("xc_images =", value, "xcImages");
            return (Criteria) this;
        }

        public Criteria andXcImagesNotEqualTo(String value) {
            addCriterion("xc_images <>", value, "xcImages");
            return (Criteria) this;
        }

        public Criteria andXcImagesGreaterThan(String value) {
            addCriterion("xc_images >", value, "xcImages");
            return (Criteria) this;
        }

        public Criteria andXcImagesGreaterThanOrEqualTo(String value) {
            addCriterion("xc_images >=", value, "xcImages");
            return (Criteria) this;
        }

        public Criteria andXcImagesLessThan(String value) {
            addCriterion("xc_images <", value, "xcImages");
            return (Criteria) this;
        }

        public Criteria andXcImagesLessThanOrEqualTo(String value) {
            addCriterion("xc_images <=", value, "xcImages");
            return (Criteria) this;
        }

        public Criteria andXcImagesLike(String value) {
            addCriterion("xc_images like", value, "xcImages");
            return (Criteria) this;
        }

        public Criteria andXcImagesNotLike(String value) {
            addCriterion("xc_images not like", value, "xcImages");
            return (Criteria) this;
        }

        public Criteria andXcImagesIn(List<String> values) {
            addCriterion("xc_images in", values, "xcImages");
            return (Criteria) this;
        }

        public Criteria andXcImagesNotIn(List<String> values) {
            addCriterion("xc_images not in", values, "xcImages");
            return (Criteria) this;
        }

        public Criteria andXcImagesBetween(String value1, String value2) {
            addCriterion("xc_images between", value1, value2, "xcImages");
            return (Criteria) this;
        }

        public Criteria andXcImagesNotBetween(String value1, String value2) {
            addCriterion("xc_images not between", value1, value2, "xcImages");
            return (Criteria) this;
        }

        public Criteria andXcTextIsNull() {
            addCriterion("xc_text is null");
            return (Criteria) this;
        }

        public Criteria andXcTextIsNotNull() {
            addCriterion("xc_text is not null");
            return (Criteria) this;
        }

        public Criteria andXcTextEqualTo(String value) {
            addCriterion("xc_text =", value, "xcText");
            return (Criteria) this;
        }

        public Criteria andXcTextNotEqualTo(String value) {
            addCriterion("xc_text <>", value, "xcText");
            return (Criteria) this;
        }

        public Criteria andXcTextGreaterThan(String value) {
            addCriterion("xc_text >", value, "xcText");
            return (Criteria) this;
        }

        public Criteria andXcTextGreaterThanOrEqualTo(String value) {
            addCriterion("xc_text >=", value, "xcText");
            return (Criteria) this;
        }

        public Criteria andXcTextLessThan(String value) {
            addCriterion("xc_text <", value, "xcText");
            return (Criteria) this;
        }

        public Criteria andXcTextLessThanOrEqualTo(String value) {
            addCriterion("xc_text <=", value, "xcText");
            return (Criteria) this;
        }

        public Criteria andXcTextLike(String value) {
            addCriterion("xc_text like", value, "xcText");
            return (Criteria) this;
        }

        public Criteria andXcTextNotLike(String value) {
            addCriterion("xc_text not like", value, "xcText");
            return (Criteria) this;
        }

        public Criteria andXcTextIn(List<String> values) {
            addCriterion("xc_text in", values, "xcText");
            return (Criteria) this;
        }

        public Criteria andXcTextNotIn(List<String> values) {
            addCriterion("xc_text not in", values, "xcText");
            return (Criteria) this;
        }

        public Criteria andXcTextBetween(String value1, String value2) {
            addCriterion("xc_text between", value1, value2, "xcText");
            return (Criteria) this;
        }

        public Criteria andXcTextNotBetween(String value1, String value2) {
            addCriterion("xc_text not between", value1, value2, "xcText");
            return (Criteria) this;
        }

        public Criteria andXcCtimeIsNull() {
            addCriterion("xc_ctime is null");
            return (Criteria) this;
        }

        public Criteria andXcCtimeIsNotNull() {
            addCriterion("xc_ctime is not null");
            return (Criteria) this;
        }

        public Criteria andXcCtimeEqualTo(Date value) {
            addCriterion("xc_ctime =", value, "xcCtime");
            return (Criteria) this;
        }

        public Criteria andXcCtimeNotEqualTo(Date value) {
            addCriterion("xc_ctime <>", value, "xcCtime");
            return (Criteria) this;
        }

        public Criteria andXcCtimeGreaterThan(Date value) {
            addCriterion("xc_ctime >", value, "xcCtime");
            return (Criteria) this;
        }

        public Criteria andXcCtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("xc_ctime >=", value, "xcCtime");
            return (Criteria) this;
        }

        public Criteria andXcCtimeLessThan(Date value) {
            addCriterion("xc_ctime <", value, "xcCtime");
            return (Criteria) this;
        }

        public Criteria andXcCtimeLessThanOrEqualTo(Date value) {
            addCriterion("xc_ctime <=", value, "xcCtime");
            return (Criteria) this;
        }

        public Criteria andXcCtimeIn(List<Date> values) {
            addCriterion("xc_ctime in", values, "xcCtime");
            return (Criteria) this;
        }

        public Criteria andXcCtimeNotIn(List<Date> values) {
            addCriterion("xc_ctime not in", values, "xcCtime");
            return (Criteria) this;
        }

        public Criteria andXcCtimeBetween(Date value1, Date value2) {
            addCriterion("xc_ctime between", value1, value2, "xcCtime");
            return (Criteria) this;
        }

        public Criteria andXcCtimeNotBetween(Date value1, Date value2) {
            addCriterion("xc_ctime not between", value1, value2, "xcCtime");
            return (Criteria) this;
        }

        public Criteria andXcTypeIsNull() {
            addCriterion("xc_type is null");
            return (Criteria) this;
        }

        public Criteria andXcTypeIsNotNull() {
            addCriterion("xc_type is not null");
            return (Criteria) this;
        }

        public Criteria andXcTypeEqualTo(Boolean value) {
            addCriterion("xc_type =", value, "xcType");
            return (Criteria) this;
        }

        public Criteria andXcTypeNotEqualTo(Boolean value) {
            addCriterion("xc_type <>", value, "xcType");
            return (Criteria) this;
        }

        public Criteria andXcTypeGreaterThan(Boolean value) {
            addCriterion("xc_type >", value, "xcType");
            return (Criteria) this;
        }

        public Criteria andXcTypeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("xc_type >=", value, "xcType");
            return (Criteria) this;
        }

        public Criteria andXcTypeLessThan(Boolean value) {
            addCriterion("xc_type <", value, "xcType");
            return (Criteria) this;
        }

        public Criteria andXcTypeLessThanOrEqualTo(Boolean value) {
            addCriterion("xc_type <=", value, "xcType");
            return (Criteria) this;
        }

        public Criteria andXcTypeIn(List<Boolean> values) {
            addCriterion("xc_type in", values, "xcType");
            return (Criteria) this;
        }

        public Criteria andXcTypeNotIn(List<Boolean> values) {
            addCriterion("xc_type not in", values, "xcType");
            return (Criteria) this;
        }

        public Criteria andXcTypeBetween(Boolean value1, Boolean value2) {
            addCriterion("xc_type between", value1, value2, "xcType");
            return (Criteria) this;
        }

        public Criteria andXcTypeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("xc_type not between", value1, value2, "xcType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table l_xiangce
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 28 13:00:42 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table l_xiangce
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}