package com.example.my_blog.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class LXiangce implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_xiangce.id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_xiangce.xc_images
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private String xcImages;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_xiangce.xc_text
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private String xcText;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_xiangce.xc_ctime
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date xcCtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column l_xiangce.xc_type
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private Integer xcType;

    private Integer xcDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table l_xiangce
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_xiangce.id
     *
     * @return the value of l_xiangce.id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_xiangce.id
     *
     * @param id the value for l_xiangce.id
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_xiangce.xc_images
     *
     * @return the value of l_xiangce.xc_images
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public String getXcImages() {
        return xcImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_xiangce.xc_images
     *
     * @param xcImages the value for l_xiangce.xc_images
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setXcImages(String xcImages) {
        this.xcImages = xcImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_xiangce.xc_text
     *
     * @return the value of l_xiangce.xc_text
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public String getXcText() {
        return xcText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_xiangce.xc_text
     *
     * @param xcText the value for l_xiangce.xc_text
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setXcText(String xcText) {
        this.xcText = xcText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_xiangce.xc_ctime
     *
     * @return the value of l_xiangce.xc_ctime
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Date getXcCtime() {
        return xcCtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_xiangce.xc_ctime
     *
     * @param xcCtime the value for l_xiangce.xc_ctime
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setXcCtime(Date xcCtime) {
        this.xcCtime = xcCtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column l_xiangce.xc_type
     *
     * @return the value of l_xiangce.xc_type
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Integer getXcType() {
        return xcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column l_xiangce.xc_type
     *
     * @param xcType the value for l_xiangce.xc_type
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public void setXcType(Integer xcType) {
        this.xcType = xcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_xiangce
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    public Integer getXcDelete() {
        return xcDelete;
    }

    public void setXcDelete(Integer xcDelete) {
        this.xcDelete = xcDelete;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", xcImages=").append(xcImages);
        sb.append(", xcText=").append(xcText);
        sb.append(", xcCtime=").append(xcCtime);
        sb.append(", xcType=").append(xcType);
        sb.append(",xc_delete=").append(xcDelete);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}