package com.example.my_blog.mapper;

import com.example.my_blog.model.LArticleTag;
import com.example.my_blog.model.LArticleTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LArticleTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article_tag
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int countByExample(LArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article_tag
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int deleteByExample(LArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article_tag
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article_tag
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int insert(LArticleTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article_tag
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int insertSelective(LArticleTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article_tag
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    List<LArticleTag> selectByExample(LArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article_tag
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    LArticleTag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article_tag
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByExampleSelective(@Param("record") LArticleTag record, @Param("example") LArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article_tag
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByExample(@Param("record") LArticleTag record, @Param("example") LArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article_tag
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByPrimaryKeySelective(LArticleTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article_tag
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByPrimaryKey(LArticleTag record);

    void deleteByPTagId(Integer id);

    void deleteByArticleId(Integer id);
}