package com.example.my_blog.mapper;

import com.example.my_blog.model.LArticleCategory;
import com.example.my_blog.model.LArticleCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LArticleCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article_category
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int countByExample(LArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article_category
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int deleteByExample(LArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article_category
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article_category
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int insert(LArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article_category
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int insertSelective(LArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article_category
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    List<LArticleCategory> selectByExample(LArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article_category
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    LArticleCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article_category
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByExampleSelective(@Param("record") LArticleCategory record, @Param("example") LArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article_category
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByExample(@Param("record") LArticleCategory record, @Param("example") LArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article_category
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByPrimaryKeySelective(LArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article_category
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByPrimaryKey(LArticleCategory record);


    void deleteByCategoryId(Integer cId);

    void deleteByArticleId(Integer id);
}