package com.example.my_blog.mapper;

import com.example.my_blog.dto.ArticleDeleteDto;
import com.example.my_blog.dto.ArticleIsRecommendDto;
import com.example.my_blog.dto.ArticleIsTopDto;
import com.example.my_blog.model.LArticle;
import com.example.my_blog.model.LArticleExample;
import java.util.List;

import com.example.my_blog.vo.*;
import org.apache.ibatis.annotations.Param;

public interface LArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int countByExample(LArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int deleteByExample(LArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int insert(LArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int insertSelective(LArticle record);

    LArticle ifRepeatArticle(String articleTitle,String articleText);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    List<LArticle> selectByExampleWithBLOBs(LArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    List<LArticle> selectByExample(LArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    LArticle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByExampleSelective(@Param("record") LArticle record, @Param("example") LArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") LArticle record, @Param("example") LArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByExample(@Param("record") LArticle record, @Param("example") LArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByPrimaryKeySelective(LArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(LArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_article
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByPrimaryKey(LArticle record);


    List<ArticleRecommendVO> selectArticleByTagId(Integer tagId,Integer fId);


    List<ArticleRecommendVO> selectArticleByCategoryId(Integer categoryId,Integer fId);


    List<LArticleVo> selectBySearch(String search);

//    找下一篇
    ArticlePaginationVO selectNextArticle(Integer articleId);

//    找上一篇
    ArticlePaginationVO selectLastArticle(Integer articleId);

//    List<LArticle> selectBySearch(String search);

//    获取主页文章
    List<ArticleHomeVo> selectArticleHome();

    /**
     * 查询推荐文章
     *
     * @return 推荐文章
     */
    List<ArticleRecommendVO> selectArticleRecommend();

    List<ArticleSearchVO> selectArticleSearchList(String search);

    String getArticleTitleById(Integer id);

    int updateIsDelete(ArticleDeleteDto articleDeleteDto);

    int updateIsTop(ArticleIsTopDto articleIsTopDto);

    int updateIsRecommend(ArticleIsRecommendDto articleIsRecommendDto);

    LArticleVo getLArticleVoById(Integer id);

    int updateRead(Integer id);

    int updateZan(Integer id);
}