package com.example.my_blog.mapper;

import com.example.my_blog.model.LArticleCategory;
import com.example.my_blog.model.LCategory;
import com.example.my_blog.model.LCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_category
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int countByExample(LCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_category
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int deleteByExample(LCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_category
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_category
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int insert(LCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_category
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int insertSelective(LCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_category
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    List<LCategory> selectByExample(LCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_category
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    LCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_category
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByExampleSelective(@Param("record") LCategory record, @Param("example") LCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_category
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByExample(@Param("record") LCategory record, @Param("example") LCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_category
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByPrimaryKeySelective(LCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_category
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */

    List<LCategory> selectBySearch(String search);

    int updateByPrimaryKey(LCategory record);

    LCategory ifRepeatLCategory(String categoryName);

    LCategory selectCategoryByArticleId(Integer articleId);
}