package com.example.my_blog.mapper;

import com.example.my_blog.model.LComment;
import com.example.my_blog.model.LCommentExample;
import java.util.List;

import com.example.my_blog.vo.LCommentsVo;
import com.example.my_blog.vo.RecentCommentVO;
import org.apache.ibatis.annotations.Param;

public interface LCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_comment
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int countByExample(LCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_comment
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int deleteByExample(LCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_comment
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_comment
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int insert(LComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_comment
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int insertSelective(LComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_comment
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    List<LComment> selectByExample(LCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_comment
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    LComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_comment
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByExampleSelective(@Param("record") LComment record, @Param("example") LCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_comment
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByExample(@Param("record") LComment record, @Param("example") LCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_comment
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByPrimaryKeySelective(LComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_comment
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByPrimaryKey(LComment record);

    List<LCommentsVo> commentList(Integer articleId);

    List<RecentCommentVO> getRentCommentList();
}