package com.example.my_blog.mapper;

import com.example.my_blog.model.LFriend;
import com.example.my_blog.model.LFriendExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LFriendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_friend
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int countByExample(LFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_friend
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int deleteByExample(LFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_friend
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_friend
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int insert(LFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_friend
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int insertSelective(LFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_friend
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    List<LFriend> selectByExample(LFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_friend
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    LFriend selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_friend
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByExampleSelective(@Param("record") LFriend record, @Param("example") LFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_friend
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByExample(@Param("record") LFriend record, @Param("example") LFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_friend
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByPrimaryKeySelective(LFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_friend
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByPrimaryKey(LFriend record);
}