package com.example.my_blog.mapper;

import com.example.my_blog.dto.LRoleIsDisableDto;
import com.example.my_blog.model.LRole;
import com.example.my_blog.model.LRoleExample;
import java.util.List;
import java.util.Set;

import com.example.my_blog.vo.RoleVo;
import org.apache.ibatis.annotations.Param;

public interface LRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_role
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int countByExample(LRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_role
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int deleteByExample(LRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_role
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_role
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int insert(LRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_role
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int insertSelective(LRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_role
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    List<LRole> selectByExample(LRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_role
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    LRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_role
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByExampleSelective(@Param("record") LRole record, @Param("example") LRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_role
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByExample(@Param("record") LRole record, @Param("example") LRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_role
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByPrimaryKeySelective(LRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_role
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByPrimaryKey(LRole record);

    List<LRole> getRoleListByUserId(Integer id);

    LRole selectByRoleName(String roleName);

    int updataRoleDisable(LRoleIsDisableDto lRoleIsDisable);

    List<RoleVo> getByUserVoId(Integer userId);
}