package com.example.my_blog.mapper;

import com.example.my_blog.model.LSuibi;
import com.example.my_blog.model.LSuibiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LSuibiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_suibi
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int countByExample(LSuibiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_suibi
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int deleteByExample(LSuibiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_suibi
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_suibi
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int insert(LSuibi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_suibi
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int insertSelective(LSuibi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_suibi
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    List<LSuibi> selectByExample(LSuibiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_suibi
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    LSuibi selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_suibi
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByExampleSelective(@Param("record") LSuibi record, @Param("example") LSuibiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_suibi
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByExample(@Param("record") LSuibi record, @Param("example") LSuibiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_suibi
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByPrimaryKeySelective(LSuibi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_suibi
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByPrimaryKey(LSuibi record);

    List<LSuibi> getAllByText(String search);
}