package com.example.my_blog.mapper;

import com.example.my_blog.dto.UserDto;
import com.example.my_blog.model.LUser;
import com.example.my_blog.model.LUserExample;
import java.util.List;

import com.example.my_blog.vo.AdminUserVo;
import com.example.my_blog.vo.LUserVo;
import com.example.my_blog.vo.UserVo;
import org.apache.ibatis.annotations.Param;

public interface LUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_user
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int countByExample(LUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_user
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int deleteByExample(LUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_user
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_user
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int insert(LUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_user
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int insertSelective(LUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_user
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    List<LUser> selectByExample(LUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_user
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    LUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_user
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByExampleSelective(@Param("record") LUser record, @Param("example") LUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_user
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByExample(@Param("record") LUser record, @Param("example") LUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_user
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByPrimaryKeySelective(LUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_user
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByPrimaryKey(LUser record);

    LUserVo getLUserVo();

    List<AdminUserVo> selectAll();

    LUser selectByUserName(String username);

    UserVo loginByUserName(String name);

}