package com.example.my_blog.mapper;

import com.example.my_blog.model.LUserRole;
import com.example.my_blog.model.LUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_user_role
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int countByExample(LUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_user_role
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int deleteByExample(LUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_user_role
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_user_role
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int insert(LUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_user_role
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int insertSelective(LUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_user_role
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    List<LUserRole> selectByExample(LUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_user_role
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    LUserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_user_role
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByExampleSelective(@Param("record") LUserRole record, @Param("example") LUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_user_role
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByExample(@Param("record") LUserRole record, @Param("example") LUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_user_role
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByPrimaryKeySelective(LUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_user_role
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByPrimaryKey(LUserRole record);


    int selectIdByUserIdandRoleId(Integer userId, Integer roleId);

    void deleteByUserId(Integer userId);

    void deleteByRoleId(Integer id);
}