package com.example.my_blog.mapper;

import com.example.my_blog.model.LVisitLog;
import com.example.my_blog.model.LVisitLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LVisitLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_visit_log
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int countByExample(LVisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_visit_log
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int deleteByExample(LVisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_visit_log
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_visit_log
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int insert(LVisitLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_visit_log
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int insertSelective(LVisitLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_visit_log
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    List<LVisitLog> selectByExample(LVisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_visit_log
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    LVisitLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_visit_log
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByExampleSelective(@Param("record") LVisitLog record, @Param("example") LVisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_visit_log
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByExample(@Param("record") LVisitLog record, @Param("example") LVisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_visit_log
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByPrimaryKeySelective(LVisitLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_visit_log
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByPrimaryKey(LVisitLog record);
}