package com.example.my_blog.mapper;

import com.example.my_blog.dto.XiangCeDto;
import com.example.my_blog.model.LXiangce;
import com.example.my_blog.model.LXiangceExample;
import java.util.List;

import com.example.my_blog.vo.LXiangceVo;
import org.apache.ibatis.annotations.Param;

public interface LXiangceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_xiangce
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int countByExample(LXiangceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_xiangce
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int deleteByExample(LXiangceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_xiangce
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_xiangce
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int insert(LXiangce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_xiangce
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int insertSelective(LXiangce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_xiangce
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    List<LXiangce> selectByExample(LXiangceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_xiangce
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    LXiangce selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_xiangce
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByExampleSelective(@Param("record") LXiangce record, @Param("example") LXiangceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_xiangce
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByExample(@Param("record") LXiangce record, @Param("example") LXiangceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_xiangce
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByPrimaryKeySelective(LXiangce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l_xiangce
     *
     * @mbggenerated Wed Jun 28 13:00:42 CST 2023
     */
    int updateByPrimaryKey(LXiangce record);

//    后台获取相册（包括删除属性）
    List<LXiangce> getXiangCeAllByText(String text);

//    前台获取所有
//    List<LXiangceVo> getXiangceList(String search);

    //    前台获取所有
    List<LXiangceVo> getXiangceListByTypeId(Integer xcType);

    List<LXiangceVo> getXiangceSize(Integer xcType);

    int updateByxcDelete(XiangCeDto xiangCeDto);

    LXiangce selectByXcText(String xcText);
}